version: '3.8'

services:
  frontend:
    image: angular
    container_name: angular
    ports:
      - "4200:80"
    networks:
      - my_network

  backend:
    image: z
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Aziz2022@"
      MYSQL_DATABASE: employeemanager
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
